project_id = "redxjak-analytics"

[functions.collect]
verify_jwt = false

[functions.dashboard-login]
verify_jwt = false

[functions.dashboard-data]
verify_jwt = false

[functions.site-content]
verify_jwt = false

[functions.admin-site]
verify_jwt = false
